name: Produce pdf diabolo pandocker

on:
  push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image on dalibo
      run: docker run --rm --volume "`pwd`:/pandoc"  --user `id -u`:`id -g` --entrypoint "bin/makedoc.sh"   dalibo/pandocker:stable
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: derKUEKeN-dalibo.pdf
        path: derKUEKeN.pdf
    - name: Build the Docker image on pandoc
      run: docker run --rm --volume "`pwd`:/data"  --user `id -u`:`id -g` --entrypoint "bin/makedoc.sh"   pandoc/latex:latest-ubuntu
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: derKUEKeN-pandoc.pdf
        path: derKUEKeN.pdf
    - name: 'Release Artifact'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          derKUEKeN-pandoc.pdf
          derKUEKeN-dalibo.pdf
        
